# Generated by Django 5.2.17 on 2026-09-03 23:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='الاسم بالكامل')),
                ('mobile_number', models.CharField(db_index=True, max_length=20, verbose_name='رقم الموبايل')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='الرقم القومي')),
                ('street_number', models.IntegerField(choices=[(1, 'شارع 1'), (2, 'شارع 2'), (3, 'شارع 3'), (4, 'شارع 4'), (5, 'شارع 5'), (6, 'شارع 6'), (7, 'شارع 7'), (8, 'شارع 8'), (9, 'شارع 9'), (10, 'شارع 10'), (11, 'شارع 11'), (12, 'شارع 12'), (13, 'شارع 13'), (14, 'شارع 14'), (15, 'شارع 15'), (16, 'شارع 16'), (17, 'شارع 17')], db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)], verbose_name='رقم الشارع')),
                ('has_guard', models.BooleanField(default=False, verbose_name='يوجد غفير')),
                ('guard_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الغفير')),
                ('guard_mobile', models.CharField(blank=True, max_length=20, verbose_name='موبايل الغفير')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='مؤرشف / محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'ordering': ['street_number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='PracticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الممارسة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الممارسة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'نوع ممارسة',
                'verbose_name_plural': 'أنواع الممارسات',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='نوع الإجراء')),
                ('entity_name', models.CharField(max_length=50, verbose_name='الكيان')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='معرف الكيان')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='القيم السابقة')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='القيم الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت العملية')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط والرقابة',
                'verbose_name_plural': 'سجلات النشاط والرقابة (Audit Logs)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='اسم / بيان المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='القيمة')),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ المصروف')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي (Cash)'), ('BANK_TRANSFER', 'تحويل بنكي / إلكتروني'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف والتفاصيل')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='صورة المستند / الفاتورة')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='السنة')),
                ('month', models.IntegerField(choices=[(1, 'شهر 1'), (2, 'شهر 2'), (3, 'شهر 3'), (4, 'شهر 4'), (5, 'شهر 5'), (6, 'شهر 6'), (7, 'شهر 7'), (8, 'شهر 8'), (9, 'شهر 9'), (10, 'شهر 10'), (11, 'شهر 11'), (12, 'شهر 12')], db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('required_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المطلوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practices', to='management.member', verbose_name='العضو')),
                ('practice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practices', to='management.practicetype', verbose_name='نوع الممارسة')),
            ],
            options={
                'verbose_name': 'ممارسة شهرية',
                'verbose_name_plural': 'الممارسات الشهرية',
                'ordering': ['-year', '-month', 'member__street_number', 'member__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي (Cash)'), ('BANK_TRANSFER', 'تحويل بنكي / إلكتروني'), ('CHEQUE', 'شيك'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_voided', models.BooleanField(db_index=True, default=False, verbose_name='ملغى')),
                ('void_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='management.member', verbose_name='العضو')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='management.practice', verbose_name='الممارسة')),
            ],
            options={
                'verbose_name': 'دفعة مالية',
                'verbose_name_plural': 'الدفعات المالية',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PRACTICE_COLLECTION', 'تحصيل ممارسة'), ('OVERPAYMENT', 'مبلغ زائد'), ('EXPENSE', 'مصروفات'), ('REFUND', 'استرداد مالي'), ('ADJUSTMENT', 'تسوية مالية')], db_index=True, max_length=30, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ المعاملة')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK_TRANSFER', 'تحويل بنكي / إلكتروني'), ('CHEQUE', 'شيك'), ('OTHER', 'أخرى')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('source_payer_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المصدر / الدافع (إذا لم يكن عضواً)')),
                ('description', models.TextField(blank=True, verbose_name='البيان / الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='management.expense', verbose_name='المصروف المرتبط')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='management.member', verbose_name='العضو')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='management.payment', verbose_name='الدفعة المرتبطة')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='management.practice', verbose_name='الممارسة')),
            ],
            options={
                'verbose_name': 'معاملة مالية',
                'verbose_name_plural': 'دفتر الأستاذ المالي (Ledger)',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم الإيصال')),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الإيصال')),
                ('status', models.CharField(choices=[('NOT_RECEIVED', 'لم تستلم من شركة الكهرباء'), ('RECEIVED', 'تم الاستلام من شركة الكهرباء'), ('DELIVERED', 'تم التسليم للعضو')], db_index=True, default='NOT_RECEIVED', max_length=20, verbose_name='حالة الإيصال')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام من الكهرباء')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم للعضو')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='صورة الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='management.member', verbose_name='العضو')),
                ('practice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='management.practice', verbose_name='الممارسة')),
            ],
            options={
                'verbose_name': 'إيصال',
                'verbose_name_plural': 'الإيصالات',
                'ordering': ['-practice__year', '-practice__month', 'member__street_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='practice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('member', 'year', 'month', 'practice_type', 'is_deleted'), name='unique_member_monthly_practice_active'),
        ),
    ]
