# Generated by Django 5.2.17 on 2026-09-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='practice',
            name='unique_member_monthly_practice_active',
        ),
    ]
