# Generated by Django 5.2.17 on 2026-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_practice_unique_member_monthly_practice_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='guard_mobile_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبايل الغفير الثاني'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='رقم الموبايل'),
        ),
    ]
