# Generated by Django 5.2.17 on 2026-09-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_member_guard_mobile_2_alter_member_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض (الموقع الجغرافي)'),
        ),
        migrations.AddField(
            model_name='member',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول (الموقع الجغرافي)'),
        ),
    ]
