# Generated by Django 5.2.17 on 2026-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_member_latitude_member_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'سكني'), ('COMMERCIAL', 'تجاري')], db_index=True, default='RESIDENTIAL', max_length=20, verbose_name='نوع العضوية'),
        ),
    ]
