# Generated by Django 5.2.17 on 2026-09-11 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_member_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='street_number',
            field=models.IntegerField(choices=[(1, 'شارع 1'), (2, 'شارع 2'), (3, 'شارع 3'), (4, 'شارع 4'), (5, 'شارع 5'), (6, 'شارع 6'), (7, 'شارع 7'), (8, 'شارع 8'), (9, 'شارع 9'), (10, 'شارع 10'), (11, 'شارع 11'), (12, 'شارع 12'), (13, 'شارع 13'), (14, 'شارع 14'), (15, 'شارع 15'), (16, 'شارع 16'), (17, 'شارع 17'), (18, 'شارع 18'), (19, 'شارع 19'), (20, 'شارع 20')], db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='رقم الشارع'),
        ),
    ]
